DROP TABLE IF EXISTS products;
CREATE TABLE IF NOT EXISTS products (id bigserial, cost int NOT NULL , title VARCHAR(255) NOT NULL, PRIMARY KEY (id));

INSERT INTO products (title, cost) VALUES ( 'Apple', 10 );
INSERT INTO products (title, cost) VALUES ( 'Banana', 20 );
INSERT INTO products (title, cost) VALUES ( 'Watermelon', 8 );
INSERT INTO products (title, cost) VALUES ( 'Orange', 12 );
INSERT INTO products (title, cost) VALUES ( 'Lemon', 13 );
INSERT INTO products (title, cost) VALUES ( 'Dragon fruit', 20 );
INSERT INTO products (title, cost) VALUES ( 'Blueberries', 15 );
INSERT INTO products (title, cost) VALUES ( 'Raspberry', 21 );
INSERT INTO products (title, cost) VALUES ( 'Strawberry', 18 );
INSERT INTO products (title, cost) VALUES ( 'Blackberry', 17 );
INSERT INTO products (title, cost) VALUES ( 'Apple x 2', 20 );
INSERT INTO products (title, cost) VALUES ( 'Banana x 2', 40 );
INSERT INTO products (title, cost) VALUES ( 'Watermelon x 2', 16 );
INSERT INTO products (title, cost) VALUES ( 'Orange x 2', 24 );
INSERT INTO products (title, cost) VALUES ( 'Lemon x 2', 26 );
INSERT INTO products (title, cost) VALUES ( 'Dragon fruit x 2', 40 );
INSERT INTO products (title, cost) VALUES ( 'Blueberries x 2', 30 );
INSERT INTO products (title, cost) VALUES ( 'Raspberry x 2', 42 );
INSERT INTO products (title, cost) VALUES ( 'Strawberry x 2', 36 );
INSERT INTO products (title, cost) VALUES ( 'Blackberry x 2', 34 );
